#!/usr/bin/env ansible-playbook 
---
- hosts: localhost
  connection: local
  # gather_facts true because we need the public ip address
  gather_facts: true

  tasks:
  - name: Deploy cluster
    import_role: 
      name: openshift-4-cluster
      tasks_from: create.yml