---

openshift_install_dir: "{{ playbook_dir }}/../{{ cluster_name }}"
ssh_public_key_location: /root/.ssh/id_rsa

vn_subnet: "192.168.45.0"
vn_internal_domain: "intrn.local"

vm_autostart: false

# Important: OpenShift version must match to RHEL CoreOS version!

# reference to OpenShift version
openshift_version: 4.5.2
openshift_install_command: "/opt/openshift-install-{{ openshift_version }}/openshift-install"

# reference to coreos qcow file
coreos_version: 4.5.2
coreos_download_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ coreos_version.split('.')[:2]|join('.') }}/{{ coreos_version }}/rhcos-{{coreos_version}}-x86_64-qemu.x86_64.qcow2.gz"
coreos_csum_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ coreos_version.split('.')[:2]|join('.') }}/{{ coreos_version }}/sha256sum.txt"

# reference to centos qcow file (CentOS-7-x86_64-GenericCloud-2003 = CentOS 7.8)
centos_download_url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2003.qcow2.xz"
centos_csum_url: "https://cloud.centos.org/centos/7/images/sha256sum.txt"

# you can check available version numbers from here:
# https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/
imgs_path: /var/lib/libvirt/images
coreos_path: /var/lib/libvirt/images
coreos_file: "rhcos-{{ coreos_version }}.qcow2"
coreos_image_location: "{{ coreos_path }}/{{ coreos_file }}"
centos_file: "CentOS-7-x86_64-GenericCloud.qcow2"
centos_image_location: "{{ imgs_path }}/{{ centos_file }}"