# These repositories are checked out from github 
#

- name: 'Check out git repos'
  git:
    repo: '{{item.value.src}}'
    dest: '{{item.value.dest}}'
    version: '{{item.value.tag}}'  
    update: no
    force: no
  with_items: '{{repos | dict2items}}' 


