---
- import_tasks: create-network.yml
  # vars:
  #   vn_public_domain: "{{ cluster_name }}.{{ public_domain }}"
  #   vn_master_count: "{{ master_count }}"
  #   vn_compute_count: "{{ compute_count }}"
  tags: network

# Add a new host in the dhcp pool
- name: Add new host to network
  virt_net:
    # name: TRYOCP2
    name: "{{ cluster_name }}"
    command: modify
    # xml: "<host name='ocp4try-console' ip='192.168.70.50' mac='52:54:00:a8:32:1f' />"
    # xml: "<host name='{{ cluster_name }}-console' ip='192.168.80.50' mac='52:54:00:a8:32:2f' />"
    xml: "<host name='{{ cluster_name }}-console' ip='{{ vn_subnet.split('.')[:3] | join('.')}}.50' mac='52:54:00:{{ '%02x' % vn_subnet.split('.')[1]|int }}:{{ '%02x' % vn_subnet.split('.')[2]|int }}:{{ '%02x' % 3 }}' />"

- name: Download OpenShift Artifacts
  include: download-openshift-artifacts.yml
  tags: download-openshift-artifacts

- name: Inject host ssh into console while creating mosipuser
  command: "virt-sysprep -a /var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2 --run-command 'useradd mosipuser' --ssh-inject mosipuser:file:/root/.ssh/id_rsa.pub"

- name: Create console node
  include: create-vm-console-centos.yml
  vars:
    vm_instance_name: "{{ cluster_name }}-console"
    vm_network: "{{ cluster_name }}"
    vm_mac_address: "52:54:00:{{ '%02x' % vn_subnet.split('.')[1]|int }}:{{ '%02x' % vn_subnet.split('.')[2]|int }}:{{ '%02x' % 3 }}"
    # vm_mac_address: "52:54:00:a8:32:2f"
    vm_vcpu: 4
    vm_memory_size: 16384
    vm_memory_unit: 'MiB'
    vm_root_disk_size: '120G'