---
- name: Download OpenShift Artifacts
  include: download-openshift-artifacts.yml
  tags: download-openshift-artifacts

# - name: Create console node
#   include: create-vm.yml
#   vars:
#     vm_instance_name: "{{ cluster_name }}-console2"
#     vm_network: "{{ cluster_name }}"
#     vm_ignition_file: "{{ openshift_install_dir }}/worker.ign"
#     vm_mac_address: "52:54:00:{{ '%02x' % vn_subnet.split('.')[1]|int }}:{{ '%02x' % vn_subnet.split('.')[2]|int }}:{{ '%02x' % 2 }}"
#     vm_vcpu: 4
#     vm_memory_size: 16384
#     vm_memory_unit: 'MiB'
#     vm_root_disk_size: '120G'