---
# # /var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2
- name: Create disk for {{ vm_instance_name }}
  command: "qemu-img create -f qcow2 -b {{ centos_image_location }} /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 {{ vm_root_disk_size }}"
  args:
    creates: "/var/lib/libvirt/images/{{ vm_instance_name }}.qcow2"

- name: Define VirtualMachine {{ vm_instance_name }}
  virt:
    name: "{{ vm_instance_name }}"
    command: define
    # xml: "{{ lookup('template', 'templates/vm-console.xml.j2') }}"
    xml: "{{ lookup('template', 'templates/vmconsole.xml.j2') }}"

- name: Inject host ssh into console while creating mosipuser
  # command: "virt-sysprep --selinux-relabel -a /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 --run-command 'useradd mosipuser' --ssh-inject mosipuser:file:/root/.ssh/id_rsa.pub"
  # command: "virt-sysprep --selinux-relabel -a /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 --run-command 'useradd –G wheel mosipuser' -root-password password:123456 --ssh-inject mosipuser:file:/root/.ssh/id_rsa.pub"
  command: "virt-sysprep --selinux-relabel -a /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 --run-command 'adduser -s /bin/bash -m -g 10 -G wheel mosipuser' -root-password password:123456  --append-line '/etc/sudoers:%wheel  ALL=(ALL)       NOPASSWD: ALL' --ssh-inject mosipuser:file:/root/.ssh/id_rsa.pub"

- name: Start VirtualMachine {{ vm_instance_name }}
  virt: 
    name: "{{ vm_instance_name }}"
    state: running
    autostart: "{{ vm_autostart }}"
