---
- name: Include OS specific part
  include: "prepare-host-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  
- name: Enable and Start libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: yes