#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  tasks:

    # Define a new network
    # - name: Define network br_nat
    #   virt_net:
    #     command: define
    #     name: br_nat
    #     xml: '{{ lookup("template", "network/bridge.xml.j2") }}'

    # # Ensure that a network is active (needs to be defined and built first)
    # - name: Active network br_nat
    #   virt_net:
    #     state: active
    #     name: TRYOCP

    # Add a new host in the dhcp pool
    - name: Add new host to network
      virt_net:
        name: TRYOCP
        command: modify
        xml: "<host name='my_vm' />"