#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  tasks:

    - name: Installing KVM Packages
      yum:
        name:
          - "@virtualization-hypervisor"
          - "@virtualization-client"
          - "@virtualization-platform"
          - "@virtualization-tools"
          # ansible virt need lxml
          - python3-lxml
          - python3-pip
        state: present

    - name: Enable and Start libvirtd
      systemd:
        name: libvirtd
        state: started
        enabled: yes